'use client'

import React, { useState } from 'react'
import { Settings, Key, Cpu, Globe, Shield, Save, Check, RefreshCw, Trash2 } from 'lucide-react'

export default function SettingsPage() {
  const [activeTab, setActiveTab] = useState<'models' | 'proxy' | 'privacy'>('models')
  const [saved, setSaved] = useState(false)

  const [geminiApiKey, setGeminiApiKey] = useState('AIzaSyD-mock-gemini-key-992182')
  const [openAiKey, setOpenAiKey] = useState('')
  const [proxyEndpoint, setProxyEndpoint] = useState('http://localhost:8000/v1/gemini-web')
  const [autoStream, setAutoStream] = useState(true)
  const [webSearchEnabled, setWebSearchEnabled] = useState(true)

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault()
    setSaved(true)
    setTimeout(() => setSaved(false), 2500)
  }

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 glass-panel p-6 rounded-2xl border border-border-default shadow-lg">
        <div>
          <h1 className="text-2xl font-bold text-text-primary flex items-center gap-2">
            <Settings className="w-6 h-6 text-accent-primary" />
            Workspace Settings
          </h1>
          <p className="text-sm text-text-secondary mt-1">
            Configure free Gemini Web Proxy endpoints, model API keys, and workspace preferences.
          </p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-2 border-b border-border-subtle pb-2">
        {[
          { id: 'models', label: 'AI Models & Keys', icon: Key },
          { id: 'proxy', label: 'Web Search & Proxy', icon: Globe },
          { id: 'privacy', label: 'Data & Storage', icon: Shield },
        ].map((tab) => {
          const Icon = tab.icon
          const isActive = activeTab === tab.id
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-4 py-2.5 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all ${
                isActive
                  ? 'bg-accent-primary text-white shadow-md'
                  : 'text-text-secondary hover:text-text-primary hover:bg-bg-surface'
              }`}
            >
              <Icon className="w-4 h-4" />
              {tab.label}
            </button>
          )
        })}
      </div>

      {/* Settings Form */}
      <form onSubmit={handleSave} className="glass-panel p-6 rounded-2xl border border-border-default space-y-6 shadow-xl bg-bg-surface">
        {activeTab === 'models' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-base font-bold text-text-primary flex items-center gap-2">
                <Cpu className="w-5 h-5 text-accent-primary" />
                Default LLM Providers
              </h3>
              <p className="text-xs text-text-muted mt-0.5">
                Nexus AI uses Google Gemini Web Proxy by default (100% Free). You can also add official API keys below.
              </p>
            </div>

            <div className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-text-primary">Gemini Web Proxy API Key (Optional)</label>
                <input
                  type="password"
                  value={geminiApiKey}
                  onChange={(e) => setGeminiApiKey(e.target.value)}
                  className="w-full bg-bg-base border border-border-default rounded-xl px-4 py-2.5 text-sm text-text-primary font-mono focus:outline-none focus:border-accent-primary"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-text-primary">OpenAI / OpenRouter API Key (Optional)</label>
                <input
                  type="password"
                  value={openAiKey}
                  onChange={(e) => setOpenAiKey(e.target.value)}
                  placeholder="sk-or-v1-..."
                  className="w-full bg-bg-base border border-border-default rounded-xl px-4 py-2.5 text-sm text-text-primary font-mono focus:outline-none focus:border-accent-primary"
                />
              </div>

              <div className="flex items-center justify-between p-4 rounded-xl bg-bg-base border border-border-subtle">
                <div>
                  <div className="text-sm font-semibold text-text-primary">Auto-Stream Responses</div>
                  <div className="text-xs text-text-muted">Stream tokens in real-time as they are generated by the model.</div>
                </div>
                <input
                  type="checkbox"
                  checked={autoStream}
                  onChange={(e) => setAutoStream(e.target.checked)}
                  className="w-5 h-5 accent-accent-primary rounded cursor-pointer"
                />
              </div>
            </div>
          </div>
        )}

        {activeTab === 'proxy' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-base font-bold text-text-primary flex items-center gap-2">
                <Globe className="w-5 h-5 text-accent-secondary" />
                Live Web Search & Reverse Proxy Configuration
              </h3>
              <p className="text-xs text-text-muted mt-0.5">
                Configure local backend reverse proxies for unlimited web queries.
              </p>
            </div>

            <div className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-text-primary">Proxy Service Base URL</label>
                <input
                  type="text"
                  value={proxyEndpoint}
                  onChange={(e) => setProxyEndpoint(e.target.value)}
                  className="w-full bg-bg-base border border-border-default rounded-xl px-4 py-2.5 text-sm text-text-primary font-mono focus:outline-none focus:border-accent-primary"
                />
              </div>

              <div className="flex items-center justify-between p-4 rounded-xl bg-bg-base border border-border-subtle">
                <div>
                  <div className="text-sm font-semibold text-text-primary">Enable Web Search Augmentation</div>
                  <div className="text-xs text-text-muted">Allow agents to query DuckDuckGo/Google search for real-time answer synthesis.</div>
                </div>
                <input
                  type="checkbox"
                  checked={webSearchEnabled}
                  onChange={(e) => setWebSearchEnabled(e.target.checked)}
                  className="w-5 h-5 accent-accent-primary rounded cursor-pointer"
                />
              </div>
            </div>
          </div>
        )}

        {activeTab === 'privacy' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-base font-bold text-text-primary flex items-center gap-2">
                <Shield className="w-5 h-5 text-emerald-400" />
                Data, Vector Indexes & Privacy
              </h3>
              <p className="text-xs text-text-muted mt-0.5">
                Manage locally cached vector databases and session history.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-sm font-bold text-rose-400">Clear Local Storage & Vector DB</div>
                  <div className="text-xs text-text-muted">Deletes all saved chat history, cached embeddings, and file indexes.</div>
                </div>
                <button
                  type="button"
                  onClick={() => alert('Local storage and vector cache successfully cleared.')}
                  className="px-3.5 py-2 rounded-xl bg-rose-500 hover:bg-rose-600 text-white font-medium text-xs flex items-center gap-1.5 shadow-md transition-all"
                >
                  <Trash2 className="w-4 h-4" /> Reset Workspace
                </button>
              </div>
            </div>
          </div>
        )}

        <div className="flex items-center justify-between pt-4 border-t border-border-subtle">
          {saved ? (
            <span className="text-xs font-semibold text-emerald-400 flex items-center gap-1.5">
              <Check className="w-4 h-4" /> Settings successfully saved!
            </span>
          ) : (
            <span className="text-xs text-text-muted">Changes apply immediately to all active AI sessions.</span>
          )}

          <button
            type="submit"
            className="px-5 py-2.5 rounded-xl bg-accent-primary hover:bg-accent-primary/90 text-white font-medium text-sm flex items-center gap-2 shadow-lg transition-all"
          >
            <Save className="w-4 h-4" /> Save Settings
          </button>
        </div>
      </form>
    </div>
  )
}
